version: '2.1'
services:
  #fitness_app_api is a node.js express API used by the application to get information from backend.
  fitness_app_api:
    image: node
    build: ./API/Fitness_APP
    command: npm start
    depends_on: 
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
    - 8080:80/tcp
    env_file:
      - Docker-variables.env
    restart: always
  
  #db is used to store users, relations etc.
  db:
    image: mysql:5.7
    command:
    - --default-authentication-plugin=mysql_native_password
    env_file:
      - Docker-variables.env
    volumes:
    - ./mysql_init/CreateDB.sql:/docker-entrypoint-initdb.d/CreateDB.sql
    restart: always
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
    - 3306:3306/tcp

  #Redis is used for session store (persistent cookies)    
  redis:
    image: redis:4.0.5-alpine
    env_file:
      - Docker-variables.env
    command: redis-server --requirepass Password1 --appendonly yes
    hostname: redis
    ports:
    - 6379:6379/tcp